= Что мне делать? :-)

Замечено, что вдумчивое описание образа своего Счастья и действий, чтобы его стало больше — полезное занятие.

https://text.sharedgoals.ru[text.sharedgoals.ru]

Этот текст — именно такое описание образов и практических шагов Что делать?

Живу в уверенности, что если образ Счастья правильный и его становится больше, то никому другому от этого не станет хуже.
Более того, уверен, что образы Счастья у многих совпадают.
А это значит, Цели в устремлениях сделать жизнь счастливой Общие.
Нужно только спокойно и обстоятельно разобраться в деталях и нюансах.

Вряд ли получится на телевизионном шоу или в других популярных форматах.
Там цели другие.
А вот в Тексте может получиться.

Поэтому Текст этот открытый и коллективный — его можно корректировать, дополнять или создать собственный, совершенно независимый, текстовый проект.

Подход для людей, далёких от разработки, может показаться сложным, но на практике всё элементарно.
Достаточно:

- зарегистрироваться в https://github.com[github.com];
- нажать в этом проекте кнопку Fork и таким образом создать свою версию текста;
- после чего можно смело редактировать текстовые файлы в формате AsciiDoc прямо на сайте или с помощью редактора (например, https://code.visualstudio.com[VS Code]);
- ваши изменения впоследствии можно будет отправить на объединение с этим текстом запросом Pull Request.

Что будет дальше — неизвестно.
Но то, что повышается осознанность и запускаются интересные мыслительные процессы — совершенно точно! :-)
