= «Вкалывают роботы — счастлив человек»
:created-date: 21.08.2023
:publication-date: 20.03.2024
:description: Роботы и Искусственный Интеллект зримо меняют привычный уклад жизни. Как это повлияет на наше Счастье в ближайшем будущем?

[#spief_story]
== Случай на ПМЭФ

Строка из песни Серёжи Сыроежкина как нельзя лучше подходит для названия главы, начать которую хочется начать историей, которая произошла на Петербургском Международном Экономическом Форуме.

[sidebar]
.Ситуация
****
В 2023 году в рамках ПМЭФ мы проводили конференцию «ИТ-Диалог» для цифровизаторов со всех российских городов.
В Мариинском дворце участники слушают доклады и задают вопросы.
Обмен мнениями.
У меня рассказ об опыте создания человеко-центричных сервисов на примере приложения ВКонтакте xref:p2-130-local.adoc#mini_app_vkontakte[«Я Здесь Живу»].
И вот, в самом конце нашей секции женщина из зала спрашивает:

— Вот вы рассказываете, как собираетесь командой, обсуждаете идеи, придумываете…
Это всё прекрасно.
Но вот у нас такой возможности, вообще же, нет!
Мы все завалены рутиной — отвечаем на вопросы граждан, предоставляем отчётность о том, как мы отвечаем гражданам, анализируем отчёты о динамике предоставления ответов гражданам и делаем предложения по улучшению процесса ответов гражданам и так далее и тому подобное.

Что делать-то?
Как начать создавать что-то новое!?

И ответ был, наверное, не очень приятным.
Во всяком случае, чувствовал я себя неловко, но и ответить хотелось:

— Там, где рутинная работа и нет места любопытству — мы, в «Цифровом Петербурге», запускаем роботов!
На задачи контроля и отчётности во множестве процессов Смольного, включая финансовый контроль, уже созданы помощники, которые работают 24 на 7 и делают эту работу за людей.
У сотрудников появляется возможность заниматься творческой и интеллектуальной деятельностью.

А дальше тишина…
Мне даже показалось, что в великолепном зале дворца повис немой возглас с ноткой обиды: «Совсем вы совесть потеряли в вашем Петербурге!»
****

[#routine_as_disease]
== Чрезмерная рутина как болезнь

Наиболее важный и невосполнимый ресурс — xref:p2-140-digital.adoc#time[наше Время].
Мы счастливы когда наша деятельность полезна, интересна, разнообразна и сбалансирована.

Результат рутинной деятельности не является бесполезным.
Но осознание, что эту деятельность можно автоматизировать, оптимизировать или даже исключить делает их очень похожими и это ужасает:

[quote, 'https://www.livelib.ru/quote/13476-zapiski-iz-mjortvogo-doma-f-m-dostoevskij[Фёдор Михайлович Достоевский]']
____
…если б захотели вполне раздавить, уничтожить человека, наказать его самым ужасным наказанием, так что самый страшный убийца содрогнулся бы от этого наказания и пугался его заранее, то стоило бы только придать работе характер совершенной, полнейшей бесполезности и бессмыслицы.
____

Если на работу с рутинной деятельностью, которая не вызывает xref:p2-110-system.adoc#noble_curiosity[любопытства], уходит бОльшая часть времени в нашей жизни, формируется дефицит xref:p1-010-happiness.adoc#moments_of_happiness_book[моментов Счастья] — созидательного Счастья, Счастья сопричастности, Счастья общения, xref:p1-020-call.adoc#sense_of_awe[благоговения при соприкосновения с вечным] и так далее.
А моменты, из которых состоит наша жизнь — основной элемент xref:p2-120-school.adoc#brief_happiness_model[количественной модели Счастья].

[#wlb]
== Работа и Жизнь

Наше общество существует в координатах капиталистического мироустройства — в конкурентной борьбе за ресурсы и в концепции эксплуатации труда.
Бороться за ресурсы самостоятельно, будучи предпринимателем или независимым артистом, объективно, видится куда большей авантюрой, чем устроиться на работу по найму.
Нужно обладать достаточной верой в себя и/или в завтрашний день, чтобы решиться на свой независимый путь.
При этом, чем дальше от xref:p1-020-call.adoc[Призвания] эта профессия, за которую платят деньги — тем больше рутины в жизни.
Появляется жёсткое разделение времени на Работу и Жизнь.
Именно так.
Работа не воспринимается как часть Жизни.

У меня никогда такого не было.
Даже не понимаю, как можно жить иначе.
Когда интересы по работе совпадают с жизнью — это Счастье.
Хотя мой рабочий путь был явно не хрестоматийным.
Логичнее набираться опыта в крупных компаниях, а потом используя лучшие практики запускать свой бизнес.
У меня же было наоборот.
В студенчестве экспериментировал с разными формами бизнеса «на коленке».
Скорее хулиганил, чем добивался заработка.
Но при этом мечтал работать в лучшей корпорации программного обеспечения.
И когда мечта сбылась — я оказался среди сотни заряженных на работу экспертов, лучших в своём деле, которые были влюблены в своё дело.

Наша работа, если её разложить на элементарные действия — обмен информацией в команде, у каждого своя роль в процессе.
Мессенджеры в корпоративной среде тогда не использовались.
Общались по всем поводам мы в почте.
Объём переписки в корпорации был феноменальным.
Утверждалось, что по количеству email на сотрудника в сутки Microsoft был первой корпорацией в мире.
Чтобы xref:p1-040-unhappiness.adoc#information_flow[не потонуть в информационном потоке] строго выдерживались правила общения — название письма в определённом формате, чёткая формулировка вопроса в начале письма, нюансы упоминаний в строках получателей TO, CC, BCC.
Целый этикет и свод правил.
Вспомнил момент с той поры.

[sidebar]
.Ситуация
****
2007 год.
Час ночи.
В Microsoft Outlook идёт групповое обсуждение поиска причины глюка при внедрении нашего продукта у важного заказчика.
Какой-то филиал Сбербанка, скорее всего, не помню точно.
Уже написано под сотню писем по теме.
И тут в дискуссию вклинивается руководитель департамента Microsoft Consulting Services:

— Может проблема в WLB?

3 минуты нет новых писем.
И вот вопрос-уточнение от Архитектора:

— Иван, ты про Load Balancing на Windows сервере?

— Нет, я про Work-Life Balance!

Все улыбнулись, переписку прекратили до утра, но такие ситуации случались очень часто.
****

Не отделяли мы работу от жизни.
Она и была нашей жизнью и мы были счастливы сообща искать причины проблем и решать сложные задачи.

[#routine_and_improvement]
== Поиск постоянных улучшений как спасение от рутины

Люди xref:p1-020-call.adoc#mbti_personalities[определённых психотипов], которым не даёт покоя благородное любопытство и несовершенство мира, но которым пришлось заниматься рутиной, стараются разглядеть отличия в повторяющихся действиях, анализируют их и пытаются оптимизировать.
Зачастую такой подход переходит в созидательную деятельность, приносящую Счастье.

Раз уж в данный момент я занимаюсь написанием Текста, приведу пример рутинной деятельности его набора.
Когда писари устали водить рукой по бумаге и рисовать одинаковые буквы — начали использовать оттиски и придумали печатные машинки.
Когда машинистки устали поправлять заклинившие молоточки рядом стоящих символов — начали скрупулёзно считать частоту использования букв в текстах, разносить рядом стоящие и сформировали раскладки — так появились привычные нам QWERTY и ФЫВАОЛДЖ.
Процесс этот не останавливается и по сей день — настоящие xref:index.adoc#introduction[душнилы] всегда найдут место для улучшений — достаточно почитать https://habr.com/ru/articles/717912/[статью об оптимизации русской раскладки клавиатуры на Хабре] или посмотреть на https://ru.ergohaven.xyz[клавиатуры наших ребят ErgoHaven].

Чувствуются родные души — хочется купить и опробовать такую клавиатуру, а заодно защитить мозги от Альцгеймера.
Возможно оптимальнее было бы надиктовывать, но писать в тишине нравится больше.

[#routine_in_enterprises]
== Рутина в крупных организациях

В государственном управлении и на крупных предприятиях большинство процессов укладывается в общую схему: сотрудник открывает определённый сайт, находит там запись, сравнивает её с другой записью из таблицы, ставит галочку в ячейку, и так далее по списку…
И в завершении, например, отправляет электронное письмо со стандартной резолюцией.
Таких процессов сотни и тысячи.
На них уходит человеко-годы только внутри одного предприятия.
И врукопашную бороться с такими задачами — подход, который соотносится с xref:p1-050-country.adoc#russian_management[русской моделью управления]: зальём задачу ресурсами, а оптимизация деятельности — это занятие для бедных.

Ведь сотрудников с базовым знанием компьютера можно легко найти на рынке и они хоть и не очень счастливы заниматься рутиной на работе, но при этом не увольняются же!
Самозанятых в процентном соотношении у нас намного меньше, чем в Европе, например.
Это не хорошо и не плохо.
Это особенности xref:p1-050-country.adoc#big_size_matters[огромной и богатой страны].

Но унывать, точно, нет причин.
Известно, что рутинные процессы можно автоматизировать с помощью информационных систем и программистов.
Но найти компанию-интегратора, разработчиков, поставить им задачу, проконтролировать и протестировать решение — непростые задачи, которые также требуют значительных ресурсов и времени.
А иногда автоматизация кажется и вовсе невозможной, т.к.
у разработанной кем-то и когда-то информационной системы отсутствует программный интерфейс, необходимый для интеграции.

[#robots_are_coming]
== Появление роботов

Открытие данных и программных интерфейсов остаётся наиважнейшим условием для цифровой трансформации и применения Искусственного Интеллекта в управлении.
Мы этим xref:p2-140-digital.adoc#api_petersburg_ru[активно занимаемся в Петербурге].
Однако обеспечить возможность доступа к данным в информационных системах, тем более государственных, быстро не получится по множеству объективных причин: соблюдение требований безопасности, бюджетные циклы, регламенты, невозможность приостановить процессы, xref:p1-050-country.adoc#russian_management[нехватка руководителей с необходимыми навыками] и так далее.

Хорошо, что сейчас можно обойти эту проблему и эмулировать действия обычных пользователей.
Агенты-роботы повторяют действия пользователя.
Читают и анализируют изображение на экране, двигают курсор мышки, нажимают кнопки и клавиши.
Как человек, но программа-робот.
Впервые о технологии имитации действий пользователя для задач автоматизации и интеграции узнал практически 20 лет назад.
В Microsoft Consulting Services такая технология называлась Customer Care Framework и предназначалась для интеграции устаревших систем.
На очень крупных предприятиях, там где рутина цветёт буйным цветом, зачастую эффективнее было применить такой костыль для неинтегрируемых, но работающих систем.
Чем создавать риски в критических, но работающих процессах, оптимизировать и внедрять новые системы — проще повторить действия пользователя.
Теперь такой подход называется Robotic Process Automation (RPA).
Последние несколько лет всё чаще говорят о No Code подходе, который не требует навыков программиста для создания новых систем и автоматизации процессов.
Роботизировать рутинный процесс можно силами аналитика, который прошёл обучение по использованию продукта.
Без привлечения профессиональных разработчиков.

[#robots_in_spb]
== Опыт роботизации Петербурга

[sidebar]
.Ситуация
****
В конце 2021 года, когда поддерживать рутинный процесс отчётности по ключевым метрикам эпидемии COVID-19 стало чересчур затратно, в Петербург пришли первые роботы.

У меня они почему-то ассоциировались с волками, которые, как санитары, освобождают лес от болезней.
За 2023 год роботы выгрызли https://t.me/skaz_spb/1803[150 тысяч человеко-часов мёртвой рутины], высвободив сотрудникам время для интеллектуальной и творческой деятельности.
А потенциал для развития роботизации колоссальный.
****

Попросил рассказать о нюансах эксперта, с которого начинается процесс определения рода деятельности и настройки робота.

[#rpa_in_action]
== Роботизация в нюансах (xref:p2-100-authors.adoc#dark_mind[Артём Суржиков])

Я долго пытался собраться с мыслями чтобы накидать каких-то слов и историй по поводу роботизации.
Признаться я скорее рассказчик чем писака, но что-то я постараюсь написать, а уж как получится.

Роботизация, звучала как очень интересная затея, но с чем её есть и что из неё может получиться никто не знал, собранные на скорую руку мнения разнились от «надо попробовать» до «с этим невозможно работать», а мы взяли и попробовали.
Первые потуги дались легко, мы добились быстрой победы с первым роботом в Комитете Финансов Санкт-Петербурга, а после него второй, и, о чудо — оказалось, что нам удалось высвободить от рутины 15 человек.
Только вдумайтесь — 15 человек после 4 недельной работы.
Учитывайте, что первого робота мы писали недели 3, изучая платформу, а второй оказался на 70% схожим с первым.
На текущий момент мы дали экономию 50 человек в день, в одном только Комитете Финансов.

Время шло, появлялись новые сценарии использования, со временем получилось, что предложенный подход в сборке информации для Жилищного Комитета, привёл не только к оптимизации времени, но и дисциплинировал сотрудников в смежных учреждениях.
Первым отзывом на затею роботизации процесса были слова «Не, не, администрации этого не будут делать», но когда за дело взялся робот, то через неделю оказалось, что 15 из 18 администраций скрупулёзно и регулярно начали отчитываться в срок.
Это изменило понимание роботизации в нашей команде, а следующий робот, занятый проверкой юридических лиц на предмет вхождения их в списки надёжных поставщиков, существенно взбодрил рынок.

Время шло, в нашем зоопарке роботы почти плодились, комитеты начали давать им имена, а порой мы могли слышать и противостояние (приятное и смешное, но всё-таки).
Так после внедрения робота в одном комитете, соседский комитет, отреагировал фразой «Как?!
Они что, нас обскакали?!
И мы хотим!» Мы, конечно же, сделали робота и им, но сама реакция радует и удивляет.
Что-ж, c'est la vie, соревновательность — это тоже здорово!

Однажды, мы попали в Архивный Комитет.
Это место особенно интересно, так как комитет соседствует с Архивом города.
Определилось несколько кандидатов на роботизацию, но директор Архива, выхватив нас из толпы, увела к себе.
Оказалось, что тут тоже есть место для роботизации — нас попросили помочь с роботизацией процессов по конвертации файлов, коих оказалось так много, что сотрудникам потребовалось бы около полутора лет.
Сделав робота за несколько дней, сэкономили им это время.
Робот, проработавший с остановками, выполнил работу за месяц!
Про это даже репортаж сделали.
Оказывается, мы можем не только про цифры и «бухгалтерию», но и про прекрасное — про Историю Петербурга!

Сотрудничество Цифрового Петербурга с Городской Жилищной Инспекцией начиналось не с роботизации, а с процесса xref:p2-130-local.adoc#mini_app_vkontakte[противодействия фальсификациям собраний собственников].
По накатанным рельсам дружеского сотрудничества запилили для них робота, заменяющего работу сразу нескольких сотрудников.
И, что самое главное, робот делает всю работу сам, без помощи и довольно таки стабильно.
Ну, как нам казалось.
Наш робот стал механизмом, который дружил между собой огонь и воду, лёд и пламень (продолжите сами дальше).
Инициатива понравилась, о ней доложили губернатору, подход поддержали.
Этого робота уже несколько раз улучшали с того момента.
Но представьте себе наши глаза, когда заказчик, увидев последние изменения, сказал: «Вы знаете, на самом деле, не очень-то верилось в подход в начале.
У меня ещё есть процессы для роботизации.
Сделаете их тоже?»

За это время мы научились расширять функционал роботов и понимаем как использовать искусственный интеллект, распознавание изображений, языковые модели, интегрироваться со сторонними системами и даже заменять роботами устаревшие информационные системы.
Но везде, во всех случаях, наше сотрудничество по созданию роботов проходит по шаблону.
В начале это неприязнь и непонимание, но в завершении это расцветающие лица людей, которые светятся в петербургской хмури при демонстрации результатов.
Стоит вспомнить и команду, которая живёт этими мини-проектами и меняет взгляды сотрудников, делая их счастливыми (кого-то на секунду, кого-то на неделю, у некоторых длится ещё больше).
Будем стараться и дальше, а идеи куда это двинуть уже есть…

[#catalogue_of_robots]
== Каталог роботизированных процессов (xref:p2-100-authors.adoc#bongiozzo[Сергей Поляков])

Очень хотелось бы всех максимально освободить от рутинной деятельности и предоставить возможность заниматься созидательной деятельностью не только в Петербурге, но и в других городах России.

Структура государственных учреждений между субъектами схожа и внутри этих организаций процессы, как правило, также напоминают друг друга.
Так и должно быть в рамках действующего и единого законодательства.
Петербург не является тут исключением и робот, сделанный для администрации Васильевского острова, скорее всего, можно будет использовать для Петроградки с незначительными изменениями.
Для другого города корректировок будет больше, но общее понимание процесса и нюансов позволит его переделать и запустить быстрее, чем делать с нуля.

Для переиспользования наших наработок создали https://rpateam.spb.ru/[каталог с описаниями этих роботов] — надеемся, что пригодится где-то ещё.

[#smart_assistants]
== Компаньоны с Искусственным Интеллектом вместо телефонов

Наиболее любопытным моментом в истории Артёма мне показался факт скептического, а иногда и враждебного, первоначального настроя к идее роботизации.
По рассказам нашего партнера, на одном из градообразующих предприятий Урала сотрудники написали жалобу в профсоюз с запросом на запрет роботизации их рутинной деятельности.
И добились одобрения.
В моей практике такое тоже было xref:p1-050-country.adoc#russian_management[на предприятии Самарской области].
Но прогресс неостановим и если дешевле и проще работу поручить роботу, в конечном итоге, он её и будет делать.

Совсем недавно, занимаясь своим здоровьем, xref:p2-140-digital.adoc#health_glucose[на своём опыте убедился в этом].

RPA-роботы сами запускают программы, нажимают кнопки в интерфейсах, копируют ячейки в таблицах, отправляют файлы по почте и так далее.
Справляются они с чёткими инструкциями намного быстрее среднестатистического сотрудника.
Не устают, работают 24 на 7.
Запускаются по запросу, по расписанию или по событию.
И не ошибаются!

Но с xref:p1-030-time.adoc#happy_tomorrow[развитием машинного зрения и больших языковых моделей] (LLM) — OpenAI ChatGPT, Google Gemini, YandexGPT, Сбер GigaChat и так далее, роботизация процессов становится ещё более перспективной технологией.
Теперь им по плечу сложные задачи — получить запрос от пользователя по почте, в мессенджере или по телефону, понять смысл вопроса, найти на него ответ во внутренних системах или поставить задачу сотруднику на отработку, написать ответ, причём персонализированный.

Так же как тексты состоят из букв и словосочетаний, процессы состоят из элементарных операций.
Например, чтобы найти и забронировать отель на отпуск надо:

* составить запрос к поисковику,
* выбрать вариант выдачи,
* перейти на сайт,
* разобраться с его навигацией,
* выбрать нужный раздел в меню,
* понять содержимое страницы,
* заполнить форму нужными параметрами,
* подтвердить бронь нажатием кнопки.

Все эти действия по отдельности уже умеют делать программы-агенты.
Языковые модели, которые из символов уверенно составляют правильные тексты, также могут из действий складывать результативные процессы.
LLM натренировали на эти операции, и для них уже придумали аналогичный термин — large actions model (LAM).
И вы уже не сможете определить, что в почте или в поддержке ответил не оператор, а робот.
Людям остаётся лишь донастраивать (fine tuning) эту модель.
В критически важных процессах потребуется визирование финального этапа ответственным человеком, но рутинная подготовительная работа уже будет сделана роботами.

Скорее всего на работе такие подходы станут широко применяться после распространения в повседневной жизни.
Год назад пробовал прожить без Google и Yandex поисковиков в течении недели и пользовался только ChatGPT.
У меня вполне получилось — всё таки формат Telegram общения для меня основной.
И вместе со стремительным развитием больших языковых моделей и сервисов, которые уже воспринимают речь и визуальный ряд, будут появляться гаджеты-компаньоны, постоянно подключенные к онлайн сервисам искусственного интеллекта.
Они неминуемо будут вытеснять привычные телефоны и сервисы.
Вот, например, одна из первых ласточек — кролик https://www.rabbit.tech/[Rabbit R1].
По ссылке 25 минутное видео с презентацией возможностей.
Забронировать отель на командировку в определенном месте, заполнить анкету для поиска нового сотрудника или подобрать новые кроссовки на лето — примеры задачек, с которыми такой компаньон должен будет справляться.

Развитие компаньонов особенно ускорится с распространением имплантов и биодатчиков, которые необязательно вживлять в мозг.
Это уже делают в компании Илона Маска Neuralink и это отличная перспектива для инвалидов, у которых такой способ становится единственной возможностью общаться.
С компаньонами типа Rabbit уже сейчас можно общаться как с человеком — голосом.
И как только будут натренированы LAM-процессы для повседневных задач типа покупок в интернет-магазине или оплаты счетов (это недалёкая перспектива), будет достаточно сказать:

[sidebar]
.Пример
****
— Кролик, сегодня подготовь оплату всех счетов и подбери кроссовки на мой размер, чтобы не боялись воды.

— Всё готово!
Вам осталось только подтвердить оплату и покупку.
Увеличился счёт за электричество на 250 рублей, по сравнению с прошлым месяцем, остальное также.
Кроссовки Вашего размера и любимой фирмы уже лежат в корзине.
Доставят завтра.
Если не понравится, откажетесь.
Детали на экране.

— Да, спасибо, подтверждаю.
****

[#love_manifest_robots]
== Любовь, Манифест, Роботы

Мы живём в xref:p1-030-time.adoc#human_body_for_happiness[интересное время], но как готовиться к xref:p1-030-time.adoc#happy_tomorrow[будущему с роботами и искусственным интеллектом]?
Что мне делать, чтобы быть готовым к переменам и не остаться без работы?

Для отца двоих детей вопрос совершенно непраздный.
А для молодых людей, которые сейчас готовятся к взрослой жизни, на мой взгляд, чуть ли не основной.
Дочь, которая с детства любит рисовать и пошла в ВУЗ на специальность художника-мультипликатора, небезосновательно забеспокоилась с выходом https://www.midjourney.com/[Midjourney], https://openai.com/sora[OpenAI Sora] и других сервисов генерации изображений и видео, которых с каждым годом будет всё больше.
Что станет с моей профессией через несколько лет?

В качестве возможного ответа мне понравился доступный формат https://www.robbo.ru/manifesto[Манифеста РОББО] от xref:p2-100-authors.adoc#pavelfrolov[Паши Фролова].
Лучше ознакомиться самостоятельно, тут перечислю наиболее важные моменты для дальнейшего обсуждения:

* Наглядно показано, как и почему роботы и Искусственный Интеллект начнут замещать профессии с повторяющимися, рутинными, то есть неживыми действиями;
* Очень доходчиво показана обратная сторона медали патентов в прорывных цифровых технологиях, которые, на мой взгляд, являются достоянием человечества;
* Много внимания уделено концепции открытого распространения знаний и кода — Open Source, сторонником которой я также являюсь;
* Рассмотрено две упрощённые ветки развития событий нашего общества на капиталистических рельсах — хорошая и не очень;
* Чтобы дети не остались без работы в любом из сценариев, Павел предлагает с малых лет их учить навыкам создания роботов.

Если детям нравится конструировать и проектировать — соглашусь.
Учитывая, что прогресс не остановить, также считаю, что уже сейчас стоит начинать использовать сервисы искусственного интеллекта в занятиях творчеством (Красота спасет мир) и наукой (xref:p2-110-system.adoc#noble_curiosity[Благородное любопытство]).
Но я бы расширил подход.

Можно спокойно заниматься любым ЛЮБИМЫМ созидательным делом.

Уверился в этом после погружения в дискуссию, как определить уровень мастерства фотографа, которая происходила в канале xref:p2-100-authors.adoc#AlexanderPetrosyan[Александра Петросяна].
Там была приведена формула, которую применима и к другим видам искусства:

[quote]
____
* Без любви и непрофессионально.
Это халтура.
* Без любви, но профессионально.
Это ремесло.
* С любовью и непрофессионально.
Это хобби.
* И с любовью и профессионально.
Это искусство.
____

Если раньше xref:p1-020-call.adoc#frequent_happiness[Следование Призванию] было иррациональным стремлением к саморазвитию в области своего Интереса и приносило Счастье.
Это был Пряник.

То теперь нейросети, как и роботы-санитары леса, уже заменяют всё, что делается без Любви.
Не только в фотографии.
Человек не имеет никаких шансов в конкуренции с Искусственным Интеллектом по части Халтуры и Ремесла в цифровых форматах.
В том, что можно сделать на компьютере по инструкции, натренировавшись.
И это тот Кнут, который невозможно будет не учитывать уже при нашей жизни.

IBM и множество других компаний, которые содержали армию маркетологов, дизайнеров, операторов — уже начинают сокращать их численность.

Поэтому если чем-то занимаешься с искренним любопытством — то можно идти в этом направлении бестрепетно.
А любишь ты это занятие или нет — можно найти ответ внутри себя — нужно лишь глубоко взглянуть внутрь.
И если Дочь уже, надеюсь, нащупывает своё Призвание, то Сыну ещё предстоит.

[#brave_new_world]
== Дивный Новый Мир

Мне видится, что человек отличается от всего нечеловеческого, прежде всего, Любовью.
Любовью к другому человеку, творчеству, знанию, земле, всему миру или Богу.
Объясняю себе Любовь как xref:p2-110-system.adoc#love_as_labor[нерациональный мотив делать что-либо не создавая последующих отношений Долженствования].
То есть — Просто так :-)

Верю, что люди от любых роботов отличаются Шилом в одном месте, которое не даёт на нём сидеть спокойно.
Хотя, казалось бы, многих из нас привычная работа (или родители) уже обеспечили всем необходимым для жизни — можно сесть перед телевизором, налить пива, успокоиться, вытащить это шило и … умереть.
Умереть, когда ещё бьётся сердце.
Стать обычной батарейкой для Матрицы и других рутинных процессов, в которых мы живём.

По какому сценарию пойдём, выберем синюю или красную таблетку?
Выбор за каждым из нас.
По мнению https://t.me/seeallochnaya/1161[экспертов] — уже в нашем поколении мы получим доступный сильный Искусственный Интеллект, способный заменить более 90% профессий сегодняшней «удалёнки».
И как будто специально, многих из нас на эту «удалёнку» предварительно загнала пандемия.

Прогресс не остановить.
И можно лишь обсуждать, в каких возможных направлениях стоит прокладывать новые рельсы.
Об этом далее.

include::../partials/time.adoc[]