= Экватор
:created-date: 03.08.2023
:publication-date: 24.11.2023
:description: Представление соавторов в начале практической части Текста.

[#practical_part]
== Вступление в практическую часть

Стремление к Счастью объединяет большую часть очень разных людей на планете.
До этого места текст был посвящён размышлениям о состоянии Счастья и влияющим на него факторов — отношений с людьми, достатка, работы, взгляда на жизнь и так далее.
Рождался текст из прочитанных книг, собственного опыта в многочисленных диалогах с друзьями, близкими и самим собой.
Текст звучал как пересказ этих рассуждений от первого лица.

В первой части я собрал вместе наблюдения, которые являлись вводными для задачи выбора направления дальнейшего движения.
Нужен вектор движения, который увеличит xref:p1-010-happiness.adoc#moments_of_happiness[частоту возникновения моментов счастья в нашем мире].
И если мы кардинально расходимся в оценках этих входных параметров, то дальнейшие рассуждения будут выглядеть необоснованными.
Поэтому важно найти компромисс по первой части и если есть, что возразить по ним или дополнить — очень хотелось бы xref:index.adoc#text_as_dialogue[услышать это].

Я верю, что люди разумные могут договориться, если они находятся в одной системе координат и стремятся к одному и тому же.
Нужно лишь запастись терпением и в случае расхождений пробовать погружаться на уровень абстракции глубже, в поиске общих смыслов и мотивов — конфликты зачастую обусловлены разными восприятиями одних и тех же слов.
Именно поэтому первая часть состоит из довольно очевидных или даже банальных наблюдений.
Но я старался их сдобрить описаниями ситуаций собственного осмысления.

Задача усложняется ещё и разностью восприятия у людей с xref:p1-020-call.adoc#mbti_personalities[разными темпераментами и психотипами], которые необходимо учитывать.

Вторая часть практическая, описывающая конкретные предложения, которые способствуют увеличению счастья.

И хочется быть максимально объективным.
Использовать численный подход.
С цифрами, как говорится, не поспоришь.
Поэтому мне нравятся xref:p1-010-happiness.adoc#happiness_model[попытки измерения Счастья], как основного мотиватора наших действий.

Всё, что будет написано далее — попытка ответа на вопрос «Что мне делать, чтобы быть счастливым?»

В Microsoft, где мне xref:p1-020-call.adoc#dream_job_checklist[посчастливилось работать], сотрудники прошли не только отличную практику управления на основе цифры, но ещё получили передовые навыки совместной работы.
И это как раз тот случай, когда одна голова хорошо — а две лучше.
Хотя двумя дело не ограничится.
И поэтому важно услышать мнения других по аналогичному вопросу и убедиться, что они не противоречат друг другу, а лишь дополняют.

Отдаю себе отчёт, что жизненный опыт бесконечно многообразен, что нейронные цепочки, психотипы и восприятие мира у всех уникальны — что прекрасно!
Формат этого текста предполагает возможность расширения и создан в концепции открытого кода (Open Source), что позволяет добавлять и учитывать взгляд других соавторов.
Текст этот не высечен в граните, является расширяемым и многообразным.
При этом я понимаю, что есть определенный фундамент, набор принципов, которые будут общими для большинства, несмотря на наше многообразие.
Также как и общее желание быть счастливыми.

Есть ещё одно требование, которое я для себя определил при создании нашего текста.
Всё, что будет написано далее в практической части, не может быть теоретизацией автора, но должно быть испытано на себе и являться причиной возникновения множественных моментов счастья.
Разных деятелей-теоретиков, которые сами были несчастливы, но благодаря эффектным манипуляциям и лидерским качествам вовлекали людей в эксперименты, оборачивающимися трагедиями, история знает немало.
На мой взгляд, только человек, умеющий быть счастливым на протяжении значительного периода времени, своим примером может определять направление для других.

В этой главе представлю всех авторов, которые уже поделились соображениями по тексту или заявили о своём желании написать свою часть.

[#andreevvs]
== Владимир Андреев

ИТ-шник с более чем 35 летним стажем, эксперт в области автоматизации корпоративных процессов, один из идеологов платформы Docsvision, MBA, Phd.
по Психологии, независимый исследователь проблематики Счастья, автор проекта «Геймификация жизни» и модели ПЭРЛ (прогрессия этапов развития личности), руководитель любительского хора, лабух, дважды дедушка (пока).

_https://www.16personalities.com/entp-personality[ENTP — Debater-Полемист]_

[#capysv]
== Евгения Васич

Православный соловецкий экскурсовод.

_https://www.16personalities.com/entj-personality[ENTJ – Commander-Командир]_

[#ewgeniyk]
== Евгений Картавченко

Отец, программист, поэт, художник.

_https://www.16personalities.com/ru/lichnost-infj[INFJ — Advocate-Заступник]_

[#mosroute]
== Алексей Кирюшин

Благодарный читатель, которому всю жизнь сказочно везло на замечательных людей и нужные тексты.

_https://www.16personalities.com/profiles/estj-a/m/24mojrdoq[ESTJ-A -Executive-Менеджер]_

[#deniskotovbukvoed]
== Денис Котов

Книжник.    

[#lobachev]
== Владимир Лобачев

IT-юрист с филологическими корнями.
Прагматик, верящий в карму.
Счастливый муж и отец двух дочерей.

_https://www.16personalities.com/ru/lichnost-infj[INFJ — Advocate-Заступник]_

[#mr_keyu]
== Денис Лунг

Отец, гедонист, коммуникатор, весельчак.
Считает себя счастливым человеком.

_https://www.16personalities.com/profiles/1078fc2db6aea[ESTP-A Entrepreneur-Предприниматель]_

[#AlexanderPetrosyan]
== Александр Петросян

Фотограф из Санкт-Петербурга, https://t.me/petrosphotos[Телеграм канал]

_https://www.16personalities.com/ru/lichnost-infp[INFP — Mediator-Посредник]_

[#liu_la]
== Людмила Полякова

_https://www.16personalities.com/profiles/4a8ab05d8df23[INFP — Mediator-Посредник]_

[#bongiozzo]
== Сергей Поляков

xref:index.adoc#introduction[Душнила], автор большей части этого текста.
Себя идентифицирует как Муж, Отец, Программист, Предприниматель, Фотограф с ценностями Православного.

_https://www.16personalities.com/profiles/588b2e7c12189[INTJ — Architect-Стратег]_

[#zpss]
== Сергей (Сергеевич) Поляков

Немного о себе — отец, разработчик и, по всей видимости, почти «топ менеджер».
Человек, имеющий большое количество разных корочек престижных вузов РФ, но при этом постоянно испытывающий «синдром самозванца».

_https://www.16personalities.com/profiles/d66aeb0678e0d[ENTP — Полемист]_

[#savvasahib]
== Савва Сахиб

Странник. Практикует православие.

_https://www.16personalities.com/ru/результаты/entj-a/m/2uenlsu9n[ENTJ-A — Commander-Командир]_

[#dark_mind]
== Артём Суржиков

Руководитель отдела

_https://www.16personalities.com/profiles/entj-a/m/5ow1aqnet[ENTJ — Commander-Командир]_

[#Denis_Strukov]
== Денис Струков

Фанат геоинформатики и аналитики.
Проводник идей геоаналитики в массы.
Обучал геомаркетингу, повышая квалификацию экономистов без экономического образования, запустил первый в РФ курс по геоаналитике для банков, не будучи банкиром.
Помогал Сбербанку развивать филиальную сеть, а x5 Group – обогнать Магнит, WB сделать первый сервис для франчайзи, чтобы не закрывать пункты вывоза заказов, а сотрудникам из Леруа Мерлен – стать лучшей командой в Мире по развитию, а геоплатформа компании до сих пор получает призы.
Работал с WalMart, в России и ещё с сотнями b2b-компаний.
15 лет назад запустил геомаркетинговый сервис Geointellect – первый в России сервис для геоаналитики, а также 5 лет назад – первый в СНГ.
Недавно завершил проект с мэрией Ташкента, который обогнал время на несколько лет вперед, дав дорогу 150+ сервисам по городской аналитике для управления городом, улучшения комфортности проживания жителей.
Кандидат технических наук.
Всегда интересовали дисциплины на стыке, многофакторный анализ, продукты для лучшего решения!
Сегодня занимаюсь интеграцией ИТ-решений для счастливых жителей городов России и других стран мира.
Отец двоих детей, счастливый муж.
Свободное время: social dance, походы, путешествия, теннис, пинг-понг, футбол, прогулки по городу, театр, ролики, бег, велосипед.

_https://www.16personalities.com/enfj-personality[ENFJ – Protagonist-Главный герой]_

[#pavelfrolov]
== Павел Фролов

[quote]
____
Всем привет!

Павел Фролов — серийный предприниматель, экспортирую образовательную робототехнику в 35+ стран мира.
Есть офисы в Финляндии, Японии и Китае.

Краткая визитка:

* Основал РОББО и ГНУ/Линуксцентр
* Ученик миллиардера Игоря Рыбакова
* Pre-master x10 Academy
* Преподаватель ИТМО и РГПУ
* Эксперт АСИ, ФСИ, РФРИТ
* Лучший социальный предприниматель России
* Победитель премии «Экспортер Года»
* Автор книги «Сила Франчайзинга: как компания ROBBO построила топовую международную EdTech франшизу»

Сооснователь:

* x10 Club СПБ
* Клуба Капитал

Резидент:

* ТПП РФ
* сообщество Equium
* сообщество EO

Ссылки:

https://www.robbo.ru[www.robbo.ru] https://robboclub.ru[www.robboclub.ru] https://linuxcenter.shop[linuxcenter.shop]

https://t.me/PavelFrolovX10[Телеграм канал]

https://www.robbo.ru/manifesto[Манифест]
____

include::../partials/time.adoc[]